#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               08             \
    left_padding                 08             \
    right_padding                08             \
    window_gap                   08             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# change padding for non-laptop screen display
displays=$(yabai -m query --displays | jq -r '.[].id')

for d in $displays; do
  if [ "$d" -eq 1 ]; then
    # Laptop
    yabai -m config --display 1 top_padding 12
  else
    # Any external
    yabai -m config --display "$d" top_padding 50
  fi
done

# no shadow test
yabai -m config window_shadow off

yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Arc$" title="^$" manage=off
yabai -m rule --add app="^Jomo$" title="^$" manage=off

# ghostty fix
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

echo "yabai configuration loaded.."

# displays fix
yabai -m signal --add event=display_added action="yabai --restart-service"
yabai -m signal --add event=display_removed action="yabai --restart-service"
yabai -m signal --add event=display_changed action="yabai --restart-service"
